ALTER TABLE audit_logs
    DROP CONSTRAINT chk_log_type;

ALTER TABLE audit_logs
    ADD CONSTRAINT chk_log_type
    CHECK (log_type IN ('ADMIN_ACTIVITY', 'ADMIN_MANAGEMENT', 'AI_METRICS_SYSTEM', 'SCRAPING_SYSTEM', 'SETTLEMENT_ACTIVITY', 'PAYMENT_ACTIVITY'));

COMMENT ON COLUMN audit_logs.log_type
    IS '로그 타입 (ADMIN_ACTIVITY / ADMIN_MANAGEMENT / AI_METRICS_SYSTEM / SCRAPING_SYSTEM / SETTLEMENT_ACTIVITY / PAYMENT_ACTIVITY)';
